import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { mkdir, mkdtemp, writeFile } from 'node:fs/promises';
import { join, dirname, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';
const project = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const require = createRequire(join(project, 'package.json'));
const { _electron } = require(process.env.CLARUNE_PLAYWRIGHT_MODULE || 'playwright');
const sharp = require(process.env.CLARUNE_SHARP_MODULE || 'sharp');
const work = await mkdtemp(join(tmpdir(), 'clarune-app-v3-'));
const report = process.env.CLARUNE_REVIEW_DIR || join(project, 'UI-review-v3/app');
await mkdir(report, { recursive: true });
const original = join(work, 'original.png'), comparison = join(work, 'comparison.png');
await sharp({ create: { width: 800, height: 600, channels: 3, background: '#ff0000' } }).png().toFile(original);
await sharp({ create: { width: 1600, height: 1200, channels: 3, background: '#0000ff' } }).png().toFile(comparison);
const env = { ...process.env }; delete env.ELECTRON_RUN_AS_NODE;
const exe = process.env.CLARUNE_PREVIEW_EXE || require('electron');
const app = await _electron.launch({ executablePath: exe, args: [...(process.env.CLARUNE_PREVIEW_EXE ? [] : [project]), `--user-data-dir=${join(work, 'profile')}`], env });
const page = await app.firstWindow(); page.setDefaultTimeout(20000);
await page.emulateMedia({ reducedMotion: 'reduce' });
await app.evaluate(({ BrowserWindow }) => { const w = BrowserWindow.getAllWindows()[0]; w.setContentSize(1280, 820); w.webContents.setBackgroundThrottling(false); });
const checks = [], errors = [];
page.on('pageerror', e => errors.push(e.message));
const check = (name, ok, detail) => { assert.ok(ok, `${name}: ${JSON.stringify(detail)}`); checks.push({ name, detail }); };
try {
  await page.getByTestId('nav-settings').waitFor();
  await page.evaluate(() => { localStorage.setItem('clarune.language', 'zh-CN'); localStorage.setItem('clarune.theme', 'light'); });
  await page.reload();
  await page.getByTestId('nav-settings').click();
  await page.getByRole('button', { name: '许可证', exact: true }).click();
  const focus = () => page.evaluate(() => ({ inside: !!document.activeElement?.closest('dialog'), text: document.activeElement?.textContent }));
  check('F06 modal focuses close button', (await focus()).inside);
  for (let n = 0; n < 8; n++) { await page.keyboard.press(n % 2 ? 'Shift+Tab' : 'Tab'); check(`F06 Tab stays modal ${n}`, (await focus()).inside, await focus()); }
  check('F06 background remains Settings', await page.getByTestId('nav-settings').getAttribute('aria-current') === 'page');
  await page.keyboard.press('Escape');
  check('F06 Escape closes', await page.getByRole('dialog').count() === 0);
  check('F06 trigger focus restored', await page.getByRole('button', { name: '许可证', exact: true }).evaluate(e => document.activeElement === e));
  await page.getByRole('button', { name: '紧凑', exact: true }).click();
  check('Compact preference applies', await page.locator('html').getAttribute('data-density') === 'compact');
  await page.reload(); await page.getByTestId('nav-settings').click();
  check('Density persists', await page.locator('html').getAttribute('data-density') === 'compact');
  await page.getByRole('button', { name: '舒适', exact: true }).click();
  await page.getByTestId('nav-enhance').click();
  await page.getByTestId('original-file-input').setInputFiles(original);
  await page.locator('.viewer-image').waitFor();
  await page.getByTestId('result-file-input').setInputFiles(comparison);
  await page.locator('.comparison-handle').waitFor();
  await page.getByRole('button', { name: '原图', exact: true }).click();
  await page.getByTestId('viewer-zoom-number').fill('150'); await page.getByTestId('viewer-zoom-number').press('Enter');
  await page.getByTestId('nav-settings').click(); await page.getByTestId('nav-enhance').click();
  check('F10 preserves original mode', await page.locator('.viewer-mode-group [aria-pressed=true]').textContent() === '原图');
  check('F10 preserves zoom', Number(await page.getByTestId('image-viewport').getAttribute('data-zoom')) === 1.5);
  await page.getByRole('button', { name: '滑动对比', exact: true }).click();
  await page.getByTestId('viewer-split-number').fill('27'); await page.getByTestId('viewer-split-number').press('Enter');
  await page.getByTestId('nav-watermark').click(); await page.getByTestId('nav-enhance').click();
  check('F10 preserves split and compare mode', await page.getByTestId('viewer-split-number').inputValue() === '27');
  await page.getByTestId('output-quality-number').fill('100'); await page.getByTestId('output-quality-number').press('Enter');
  for (const target of ['original', 'comparison']) {
    await page.getByTestId('export-source').selectOption(target);
    check(`F07 explicit ${target} button`, (await page.getByTestId('compression-export').textContent()).includes(target === 'original' ? '原图' : '对比图'));
    const path = join(work, `export-${target}.png`);
    await app.evaluate(({ dialog }, filePath) => { dialog.showSaveDialog = async () => ({ canceled: false, filePath }); }, path);
    await page.getByTestId('compression-export').click(); await page.getByTestId('compression-saved').waitFor();
    const out = await sharp(path).raw().toBuffer({ resolveWithObject: true });
    check(`F07 ${target} export pixels`, [...out.data.subarray(0,3)].join(',') === (target === 'original' ? '255,0,0' : '0,0,255'));
    check(`F07 ${target} export size`, out.info.width === (target === 'original' ? 800 : 1600));
  }
  await page.getByTestId('nav-history').click();
  check('Output history records success', await page.getByTestId('history-entry').count() === 2);
  await page.getByRole('button', { name: '复制路径', exact: true }).first().click();
  check('History copy path works', (await app.evaluate(({ clipboard }) => clipboard.readText())).endsWith('export-comparison.png'));
  await page.screenshot({ path: join(report, 'history.png') });
  await page.reload(); await page.getByTestId('nav-history').click();
  check('History persists after reload', await page.getByTestId('history-entry').count() === 2);
  await page.getByRole('button', { name: '清空记录', exact: true }).click();
  check('History clear leaves output files', (await sharp(join(work, 'export-original.png')).metadata()).width === 800);
  await page.getByTestId('nav-settings').click(); await page.getByRole('button', { name: 'English', exact: true }).click();
  await page.getByRole('button', { name: 'Dark', exact: true }).click();
  await page.getByRole('button', { name: 'License', exact: true }).click();
  await page.screenshot({ path: join(report, 'english-dark-license.png') }); await page.keyboard.press('Escape');
  check('No renderer exceptions', errors.length === 0, errors);
  console.log(JSON.stringify({ passed: checks.length, work, exe, errors }));
} catch (error) { await page.screenshot({ path: join(report, 'failure.png') }).catch(() => {}); throw error; }
finally { await writeFile(join(report, 'app-regression.json'), JSON.stringify({ date: new Date().toISOString(), exe, work, checks, errors }, null, 2)); await app.close(); }
